### ISSUE TITLE
Ruby Group Capstone: Kanban Board Setup

### ISSUE THREAD

**Issue by PraisesPJMT** [PraisesPJMT/Personal-Catalog#19]
## Project Link
- Project Kanban Link: [https://github.com/users/PraisesPJMT/projects/2](https://github.com/users/PraisesPJMT/projects/2)
- Repository Link: [https://github.com/PraisesPJMT/Personal-Catalog](https://github.com/PraisesPJMT/Personal-Catalog)

## Team Members
Here are the team members working on this project.
- Member 1: Benard Pacho (@benardop)
- Member 2: Praises Tula (@PraisesPJMT)
- Member 3: Shaquille Ndunda (@shaqdeff)

## Team Tasks
This is how project tasks are distributed to team members.
- Group Task: Tasks #1, #8, & #18
- Member 1 (@benardop): Tasks #2, #3, #9, #12, & #15
- Member 2 (@PraisesPJMT): Tasks #4, #5, #10, #13, & #16
- Member 3 (@shaqdeff): Tasks #6, #7, #11, #14, & #17

Happy Reviewing!!!!

**Comment by TedLivist** [comment]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @PraisesPJMT and @benardop,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You provided the link to your repo instead of the Kanban board. Kindly provide the correct link.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by PraisesPJMT** [comment]
Acknowledge! @TedLivist 
Thanks for the feedback!

We made an oversight by mistaking the instruction stated to be the link to our `GitHub Project` rather than the `Kanbard Board`
![Web capture_21-11-2022_144419_github com](https://user-images.githubusercontent.com/101870993/203070778-695831f4-e954-41c0-b99d-b22b68df2a8c.jpeg)

We just made the modification to include the link to the `Kanban Board`. :slightly_smiling_face: 

Happy Reviewing!!!

**Comment by PraisesPJMT** [comment]
Team Member 3 (@shaqdeff) Is yet to accept the invitation for the project. 
So we took a decision as a team to proceed with the Project with the team members available pending a formal response from @shaqdeff.

**Comment by mukhammadrizooff** [comment]
Hi @TEAM, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

There is a partner issue please report link on the dashboard, contact with the student success team and explain to them why 3 partners are not participating in this project. If they allow it, please resubmit this issue link and then your project will be reviewed. Good luck 😃 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by ShadyShawkat** [comment]
## Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
